version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: \${DB_HOST}
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: \${DB_PASSWORD}
      WORDPRESS_DB_NAME: db_wordpress
    volumes:
      - /mnt/efs/wordpress:/var/www/html

volumes:
  wordpress_data:
